import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ExternalLink, KeyRound, Save, Trash2 } from "lucide-react";
import { Link } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { api, getRefreshToken } from "../../../lib/api-client";
import { useAuth } from "../../auth/auth-context";
import { Button, Card, Input } from "../../../components/ui/basic";
import { AiSettingsSection } from "../ai/ai-settings-section";

type Preferences = {
  notifications: {
    approvalInApp: boolean;
    stockAlertEmail: boolean;
    expiryAlertEmail: boolean;
    dailySummaryEmail: boolean;
  };
  ui: {
    compactTables: boolean;
    defaultPageSize: number;
    currency: "USD";
    dateFormat: "MM/dd/yyyy";
  };
  roadmap: {
    aiPromoSuggestion: boolean;
    posScannerIntegration: boolean;
    advancedBiReports: boolean;
  };
};

type SystemSettings = {
  profile: {
    storeName: string;
    branchName: string;
    address: string;
    contactPhone: string;
    contactEmail: string;
    taxCode: string;
  };
  operations: {
    lowStockThreshold: number;
    defaultReorderLevel: number;
    approvalBellRefreshSeconds: number;
    dashboardActivityRefreshSeconds: number;
    recentActivityLimit: number;
  };
  reports: {
    preparedBy: string;
    footerNote: string;
    includeContactInExport: boolean;
  };
};

type SavedFilterScope = "products" | "inventory" | "expiry";

const defaultPreferences: Preferences = {
  notifications: {
    approvalInApp: true,
    stockAlertEmail: false,
    expiryAlertEmail: false,
    dailySummaryEmail: false,
  },
  ui: {
    compactTables: false,
    defaultPageSize: 20,
    currency: "USD",
    dateFormat: "MM/dd/yyyy",
  },
  roadmap: {
    aiPromoSuggestion: false,
    posScannerIntegration: false,
    advancedBiReports: false,
  },
};

const defaultSystemSettings: SystemSettings = {
  profile: {
    storeName: "Smart Supermarket",
    branchName: "Main Branch",
    address: "",
    contactPhone: "",
    contactEmail: "",
    taxCode: "",
  },
  operations: {
    lowStockThreshold: 5,
    defaultReorderLevel: 5,
    approvalBellRefreshSeconds: 5,
    dashboardActivityRefreshSeconds: 4,
    recentActivityLimit: 5,
  },
  reports: {
    preparedBy: "Operations Manager",
    footerNote: "Generated by Smart Supermarket Product Management System.",
    includeContactInExport: true,
  },
};

const parseQueryInput = (raw: string) => {
  const params = new URLSearchParams(raw);
  const out: Record<string, string> = {};
  for (const [k, v] of params.entries()) out[k] = v;
  return out;
};

const scopeRoute: Record<SavedFilterScope, string> = {
  products: "/products",
  inventory: "/inventory",
  expiry: "/expiry",
};

export const SettingsPage = () => {
  const { t } = useTranslation();
  const { user } = useAuth();
  const qc = useQueryClient();

  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  const [prefs, setPrefs] = useState<Preferences>(defaultPreferences);
  const [system, setSystem] = useState<SystemSettings>(defaultSystemSettings);

  const [filterName, setFilterName] = useState("");
  const [filterScope, setFilterScope] = useState<SavedFilterScope>("products");
  const [filterQuery, setFilterQuery] = useState("");

  const [passwordForm, setPasswordForm] = useState({
    currentPassword: "",
    newPassword: "",
    confirmPassword: "",
  });

  const canEditSystem = ["ADMIN", "MANAGER"].includes(user?.role ?? "");

  const preferencesQuery = useQuery({
    queryKey: ["settings-preferences"],
    queryFn: () => api<any>("/settings/preferences"),
  });

  const systemQuery = useQuery({
    queryKey: ["settings-system"],
    queryFn: () => api<any>("/settings/system"),
  });

  const savedFiltersQuery = useQuery({
    queryKey: ["settings-saved-filters"],
    queryFn: () => api<any>("/settings/saved-filters"),
  });
  const permissionMatrixQuery = useQuery({
    queryKey: ["settings-permission-matrix"],
    queryFn: () => api<any>("/settings/permission-matrix"),
    enabled: canEditSystem,
  });
  const sessionsQuery = useQuery({
    queryKey: ["auth-sessions"],
    queryFn: () => api<any>("/auth/sessions"),
  });

  useEffect(() => {
    if (preferencesQuery.data?.data) setPrefs(preferencesQuery.data.data);
  }, [preferencesQuery.data]);

  useEffect(() => {
    if (systemQuery.data?.data) setSystem(systemQuery.data.data);
  }, [systemQuery.data]);

  const updatePreferencesMutation = useMutation({
    mutationFn: () => api<any>("/settings/preferences", { method: "PUT", body: JSON.stringify(prefs) }),
    onSuccess: async () => {
      setMessage(t("pages.settings.messages.personalSaved"));
      setError("");
      await qc.invalidateQueries({ queryKey: ["settings-preferences"] });
    },
    onError: (e) => setError((e as Error).message),
  });

  const updateSystemMutation = useMutation({
    mutationFn: () => api<any>("/settings/system", { method: "PUT", body: JSON.stringify(system) }),
    onSuccess: async () => {
      setMessage(t("pages.settings.messages.systemSaved"));
      setError("");
      await Promise.all([
        qc.invalidateQueries({ queryKey: ["settings-system"] }),
        qc.invalidateQueries({ queryKey: ["kpi"] }),
        qc.invalidateQueries({ queryKey: ["recent"] }),
        qc.invalidateQueries({ queryKey: ["products"] }),
        qc.invalidateQueries({ queryKey: ["approval-pending-count"] }),
      ]);
    },
    onError: (e) => setError((e as Error).message),
  });

  const createFilterMutation = useMutation({
    mutationFn: () => api<any>("/settings/saved-filters", {
      method: "POST",
      body: JSON.stringify({
        name: filterName.trim(),
        scope: filterScope,
        query: parseQueryInput(filterQuery),
      }),
    }),
    onSuccess: async () => {
      setMessage(t("pages.settings.savedFilters.messages.created"));
      setError("");
      setFilterName("");
      setFilterQuery("");
      await qc.invalidateQueries({ queryKey: ["settings-saved-filters"] });
    },
    onError: (e) => setError((e as Error).message),
  });

  const deleteFilterMutation = useMutation({
    mutationFn: (id: string) => api<any>(`/settings/saved-filters/${id}`, { method: "DELETE" }),
    onSuccess: async () => {
      setMessage(t("pages.settings.savedFilters.messages.deleted"));
      setError("");
      await qc.invalidateQueries({ queryKey: ["settings-saved-filters"] });
    },
    onError: (e) => setError((e as Error).message),
  });

  const revokeSessionMutation = useMutation({
    mutationFn: (sessionId: string) =>
      api<any>("/auth/sessions/revoke", { method: "POST", body: JSON.stringify({ sessionId }) }),
    onSuccess: async () => {
      setMessage(t("pages.settings.sessions.messages.sessionRevoked"));
      setError("");
      await qc.invalidateQueries({ queryKey: ["auth-sessions"] });
    },
    onError: (e) => setError((e as Error).message),
  });

  const revokeOtherSessionsMutation = useMutation({
    mutationFn: () =>
      api<any>("/auth/sessions/revoke-others", {
        method: "POST",
        body: JSON.stringify({ currentRefreshToken: getRefreshToken() ?? undefined }),
      }),
    onSuccess: async (result) => {
      setMessage(`${t("pages.settings.sessions.messages.othersRevoked")} ${result?.data?.revoked ?? 0}`);
      setError("");
      await qc.invalidateQueries({ queryKey: ["auth-sessions"] });
    },
    onError: (e) => setError((e as Error).message),
  });

  const changePasswordMutation = useMutation({
    mutationFn: () => api<any>("/settings/change-password", {
      method: "PATCH",
      body: JSON.stringify({
        currentPassword: passwordForm.currentPassword,
        newPassword: passwordForm.newPassword,
      }),
    }),
    onSuccess: async () => {
      setMessage("Password updated.");
      setError("");
      setPasswordForm({ currentPassword: "", newPassword: "", confirmPassword: "" });
      await qc.invalidateQueries({ queryKey: ["recent"] });
    },
    onError: (e) => setError((e as Error).message),
  });

  const queryError = (preferencesQuery.error ?? systemQuery.error ?? savedFiltersQuery.error ?? sessionsQuery.error ?? permissionMatrixQuery.error) as Error | null;
  const savedFilters = savedFiltersQuery.data?.data ?? [];
  const sessions = sessionsQuery.data?.data ?? [];

  const filterLinks = useMemo(() => {
    return savedFilters.map((f: any) => {
      const scope = (f.scope ?? "products") as SavedFilterScope;
      const route = scopeRoute[scope] ?? "/products";
      const params = new URLSearchParams(f.query ?? {});
      return { ...f, href: `${route}?${params.toString()}` };
    });
  }, [savedFilters]);

  const canSubmitPasswordChange = useMemo(() => {
    if (!passwordForm.currentPassword || !passwordForm.newPassword) return false;
    if (passwordForm.newPassword.length < 8) return false;
    if (passwordForm.newPassword !== passwordForm.confirmPassword) return false;
    return true;
  }, [passwordForm]);

  return (
    <div className="space-y-5">
      {message ? <Card><p className="text-sm text-[#315f3d]">{message}</p></Card> : null}
      {error ? <Card><p className="text-sm text-[#9c4326]">{error}</p></Card> : null}
      {queryError ? <Card><p className="text-sm text-[#9c4326]">{queryError.message}</p></Card> : null}

      <section className={`space-y-3 rounded-md border p-3 ${canEditSystem ? "border-[#ead6aa] bg-[#fff9ee]/70" : "border-[#ead6aa] bg-[#fff9ee]/70"}`}>
        <div className="flex flex-wrap items-start justify-between gap-3 rounded-md border bg-[#fff9ee] px-4 py-3">
          <div>
            <h2 className="text-base font-semibold">{t("pages.settings.system.title")}</h2>
            <p className="text-xs text-[#6d5935]">
              {t("pages.settings.system.subtitle")}
            </p>
            <p className={`mt-1 text-xs ${canEditSystem ? "text-[#315f3d]" : "text-[#8b6727]"}`}>
              {canEditSystem
                ? t("pages.settings.system.notice")
                : t("pages.settings.personal.readonlyNotice")}
            </p>
          </div>
          <Button
            className="inline-flex items-center gap-2"
            onClick={() => updateSystemMutation.mutate()}
            disabled={!canEditSystem || updateSystemMutation.isPending || systemQuery.isLoading}
          >
            <Save size={14} />
            {updateSystemMutation.isPending ? t("pages.settings.messages.saving") : t("pages.settings.system.button")}
          </Button>
        </div>

        <Card>
          <h3 className="mb-3 text-base font-semibold">{t("pages.settings.system.profile.title")}</h3>
        <div className="grid gap-3 md:grid-cols-2">
          <div>
            <div className="mb-1 text-xs text-muted-warm">{t("pages.settings.system.profile.storeName")}</div>
            <Input
              value={system.profile.storeName}
              disabled={!canEditSystem}
              onChange={(e) => setSystem({ ...system, profile: { ...system.profile, storeName: e.target.value } })}
            />
          </div>
          <div>
            <div className="mb-1 text-xs text-muted-warm">{t("pages.settings.system.profile.branchName")}</div>
            <Input
              value={system.profile.branchName}
              disabled={!canEditSystem}
              onChange={(e) => setSystem({ ...system, profile: { ...system.profile, branchName: e.target.value } })}
            />
          </div>
          <div>
            <div className="mb-1 text-xs text-muted-warm">{t("pages.settings.system.profile.address")}</div>
            <Input
              value={system.profile.address}
              disabled={!canEditSystem}
              onChange={(e) => setSystem({ ...system, profile: { ...system.profile, address: e.target.value } })}
            />
          </div>
          <div>
            <div className="mb-1 text-xs text-muted-warm">{t("pages.settings.system.profile.contactPhone")}</div>
            <Input
              value={system.profile.contactPhone}
              disabled={!canEditSystem}
              onChange={(e) => setSystem({ ...system, profile: { ...system.profile, contactPhone: e.target.value } })}
            />
          </div>
          <div>
            <div className="mb-1 text-xs text-muted-warm">{t("pages.settings.system.profile.contactEmail")}</div>
            <Input
              value={system.profile.contactEmail}
              disabled={!canEditSystem}
              onChange={(e) => setSystem({ ...system, profile: { ...system.profile, contactEmail: e.target.value } })}
            />
          </div>
          <div>
            <div className="mb-1 text-xs text-muted-warm">{t("pages.settings.system.profile.taxCode")}</div>
            <Input
              value={system.profile.taxCode}
              disabled={!canEditSystem}
              onChange={(e) => setSystem({ ...system, profile: { ...system.profile, taxCode: e.target.value } })}
            />
          </div>
        </div>
        </Card>

        <Card>
          <h3 className="mb-3 text-base font-semibold">{t("pages.settings.system.operations.title")}</h3>
        <div className="grid gap-3 md:grid-cols-3">
          <div>
            <div className="mb-1 text-xs text-muted-warm">{t("pages.settings.system.operations.lowStockThreshold")}</div>
            <Input
              type="number"
              min={0}
              value={system.operations.lowStockThreshold}
              disabled={!canEditSystem}
              onChange={(e) => setSystem({
                ...system,
                operations: {
                  ...system.operations,
                  lowStockThreshold: Number(e.target.value || 0),
                },
              })}
            />
          </div>
          <div>
            <div className="mb-1 text-xs text-muted-warm">{t("pages.settings.system.operations.defaultReorderLevel")}</div>
            <Input
              type="number"
              min={0}
              value={system.operations.defaultReorderLevel}
              disabled={!canEditSystem}
              onChange={(e) => setSystem({
                ...system,
                operations: {
                  ...system.operations,
                  defaultReorderLevel: Number(e.target.value || 0),
                },
              })}
            />
          </div>
          <div>
            <div className="mb-1 text-xs text-muted-warm">{t("pages.settings.system.operations.recentActivitiesCount")}</div>
            <Input
              type="number"
              min={3}
              max={30}
              value={system.operations.recentActivityLimit}
              disabled={!canEditSystem}
              onChange={(e) => setSystem({
                ...system,
                operations: {
                  ...system.operations,
                  recentActivityLimit: Number(e.target.value || 5),
                },
              })}
            />
          </div>
          <div>
            <div className="mb-1 text-xs text-muted-warm">{t("pages.settings.system.operations.approvalBellRefresh")}</div>
            <Input
              type="number"
              min={2}
              max={120}
              value={system.operations.approvalBellRefreshSeconds}
              disabled={!canEditSystem}
              onChange={(e) => setSystem({
                ...system,
                operations: {
                  ...system.operations,
                  approvalBellRefreshSeconds: Number(e.target.value || 5),
                },
              })}
            />
          </div>
          <div>
            <div className="mb-1 text-xs text-muted-warm">{t("pages.settings.system.operations.dashboardRefresh")}</div>
            <Input
              type="number"
              min={2}
              max={120}
              value={system.operations.dashboardActivityRefreshSeconds}
              disabled={!canEditSystem}
              onChange={(e) => setSystem({
                ...system,
                operations: {
                  ...system.operations,
                  dashboardActivityRefreshSeconds: Number(e.target.value || 4),
                },
              })}
            />
          </div>
        </div>
        <p className="mt-3 text-xs text-muted-warm">
          These values are applied to low-stock KPI/filtering and live refresh behavior in the app shell and dashboard.
        </p>
        </Card>

        <Card>
          <h3 className="mb-3 text-base font-semibold">{t("pages.settings.system.report.title")}</h3>
        <div className="grid gap-3 md:grid-cols-2">
          <div>
            <div className="mb-1 text-xs text-muted-warm">{t("pages.settings.system.report.preparedBy")}</div>
            <Input
              value={system.reports.preparedBy}
              disabled={!canEditSystem}
              onChange={(e) => setSystem({ ...system, reports: { ...system.reports, preparedBy: e.target.value } })}
            />
          </div>
          <label className="inline-flex items-center gap-2 pt-6 text-sm">
            <input
              type="checkbox"
              checked={system.reports.includeContactInExport}
              disabled={!canEditSystem}
              onChange={(e) => setSystem({ ...system, reports: { ...system.reports, includeContactInExport: e.target.checked } })}
            />
            {t("pages.settings.system.report.includeStoreContact")}
          </label>
          <div className="md:col-span-2">
            <div className="mb-1 text-xs text-muted-warm">{t("pages.settings.system.report.footerNote")}</div>
            <textarea
              className="field-warm min-h-24 w-full rounded border px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-[#bb9645]/25"
              value={system.reports.footerNote}
              disabled={!canEditSystem}
              onChange={(e) => setSystem({ ...system, reports: { ...system.reports, footerNote: e.target.value } })}
            />
          </div>
        </div>
        </Card>

        {canEditSystem ? <AiSettingsSection /> : null}

        <Card>
          <h3 className="mb-3 text-base font-semibold">{t("pages.settings.sessions.title")}</h3>
          <div className="mb-3 flex justify-end">
            <Button
              className="btn-danger-warm h-9 px-3 text-xs"
              onClick={() => revokeOtherSessionsMutation.mutate()}
              disabled={revokeOtherSessionsMutation.isPending}
            >
              {revokeOtherSessionsMutation.isPending ? t("pages.settings.messages.saving") : t("pages.settings.sessions.buttons.revokeOthers")}
            </Button>
          </div>
          <div className="overflow-auto">
            <table className="table-warm w-full min-w-[860px] text-sm">
              <thead>
                <tr>
                  <th className="px-3 py-2 text-left">{t("pages.settings.sessions.table.headers.device")}</th>
                  <th className="px-3 py-2 text-left">{t("pages.settings.sessions.table.headers.ip")}</th>
                  <th className="px-3 py-2 text-left">{t("pages.settings.sessions.table.headers.created")}</th>
                  <th className="px-3 py-2 text-left">{t("pages.settings.sessions.table.headers.lastActive")}</th>
                  <th className="px-3 py-2 text-left">{t("pages.settings.sessions.table.headers.status")}</th>
                  <th className="px-3 py-2 text-right">{t("common.edit")}</th>
                </tr>
              </thead>
              <tbody>
                {sessionsQuery.isLoading ? (
                  <tr><td colSpan={6} className="px-3 py-6 text-center text-muted-warm">{t("pages.settings.sessions.table.states.loading")}</td></tr>
                ) : null}
                {!sessionsQuery.isLoading && !sessions.length ? (
                  <tr><td colSpan={6} className="px-3 py-6 text-center text-muted-warm">{t("pages.settings.sessions.table.states.empty")}</td></tr>
                ) : null}
                {sessions.map((s: any) => (
                  <tr key={s.id} className="border-b">
                    <td className="px-3 py-2">{s.deviceLabel ?? "-"}</td>
                    <td className="px-3 py-2">{s.ipAddress ?? "-"}</td>
                    <td className="px-3 py-2">{new Date(s.createdAt).toLocaleString()}</td>
                    <td className="px-3 py-2">{new Date(s.lastActiveAt).toLocaleString()}</td>
                    <td className="px-3 py-2">
                      <span className={`inline-flex rounded px-2 py-1 text-xs font-medium ${s.revokedAt ? "bg-slate-200 text-slate-700" : "bg-emerald-100 text-emerald-700"}`}>
                        {s.revokedAt ? t("pages.settings.sessions.table.status.revoked") : t("pages.settings.sessions.table.status.active")}
                      </span>
                    </td>
                    <td className="px-3 py-2 text-right">
                      <Button
                        className="btn-danger-warm h-8 px-3 text-xs"
                        disabled={Boolean(s.revokedAt) || revokeSessionMutation.isPending}
                        onClick={() => revokeSessionMutation.mutate(s.id)}
                      >
                        {t("pages.settings.sessions.buttons.revoke")}
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      </section>

      <section className="space-y-3 rounded-md border border-[#ead6aa] bg-[#fff9ee] p-3">
        <div className="rounded-md border bg-[#f7ebd5] px-4 py-3">
          <h2 className="text-base font-semibold">{t("pages.settings.personal.title")}</h2>
          <p className="text-xs text-[#6d5935]">
            {t("pages.settings.personal.notice")} <span className="font-medium">{user?.email ?? "-"}</span>
          </p>
        </div>

        <Card>
          <h3 className="mb-3 text-base font-semibold">{t("pages.settings.personal.subtitle")}</h3>
        <div className="grid gap-3 md:grid-cols-2">
          <label className="inline-flex items-center gap-2 text-sm">
            <input
              type="checkbox"
              checked={prefs.notifications.approvalInApp}
              onChange={(e) => setPrefs({ ...prefs, notifications: { ...prefs.notifications, approvalInApp: e.target.checked } })}
            />
            {t("pages.settings.personal.preferences.notifications.inAppApprovals")}
          </label>
          <label className="inline-flex items-center gap-2 text-sm">
            <input
              type="checkbox"
              checked={prefs.notifications.stockAlertEmail}
              onChange={(e) => setPrefs({ ...prefs, notifications: { ...prefs.notifications, stockAlertEmail: e.target.checked } })}
            />
            {t("pages.settings.personal.preferences.notifications.stockAlert")}
          </label>
          <label className="inline-flex items-center gap-2 text-sm">
            <input
              type="checkbox"
              checked={prefs.notifications.expiryAlertEmail}
              onChange={(e) => setPrefs({ ...prefs, notifications: { ...prefs.notifications, expiryAlertEmail: e.target.checked } })}
            />
            {t("pages.settings.personal.preferences.notifications.expiryAlert")}
          </label>
          <label className="inline-flex items-center gap-2 text-sm">
            <input
              type="checkbox"
              checked={prefs.notifications.dailySummaryEmail}
              onChange={(e) => setPrefs({ ...prefs, notifications: { ...prefs.notifications, dailySummaryEmail: e.target.checked } })}
            />
            {t("pages.settings.personal.preferences.notifications.dailySummary")}
          </label>
          <label className="inline-flex items-center gap-2 text-sm">
            <input
              type="checkbox"
              checked={prefs.ui.compactTables}
              onChange={(e) => setPrefs({ ...prefs, ui: { ...prefs.ui, compactTables: e.target.checked } })}
            />
            {t("pages.settings.personal.preferences.ui.compactDensity")}
          </label>
          <div>
            <div className="mb-1 text-xs text-muted-warm">{t("pages.settings.personal.preferences.ui.defaultPageSize")}</div>
            <select
              className="field-warm h-11 w-full rounded border px-3 text-sm outline-none focus:ring-2 focus:ring-[#bb9645]/25"
              value={String(prefs.ui.defaultPageSize)}
              onChange={(e) => setPrefs({ ...prefs, ui: { ...prefs.ui, defaultPageSize: Number(e.target.value) } })}
            >
              <option value="10">10</option>
              <option value="20">20</option>
              <option value="50">50</option>
              <option value="100">100</option>
            </select>
          </div>
        </div>
        <div className="mt-3">
          <Button onClick={() => updatePreferencesMutation.mutate()} disabled={updatePreferencesMutation.isPending || preferencesQuery.isLoading}>
            {updatePreferencesMutation.isPending ? t("pages.settings.messages.saving") : t("pages.settings.personal.button")}
          </Button>
        </div>
        </Card>

        <Card>
          <h3 className="mb-3 text-base font-semibold">{t("pages.settings.personal.password.title")}</h3>
        <div className="grid gap-3 md:grid-cols-3">
          <Input
            type="password"
            placeholder={t("pages.settings.personal.password.currentPassword")}
            value={passwordForm.currentPassword}
            onChange={(e) => setPasswordForm({ ...passwordForm, currentPassword: e.target.value })}
          />
          <Input
            type="password"
            placeholder={t("pages.settings.personal.password.newPassword")}
            value={passwordForm.newPassword}
            onChange={(e) => setPasswordForm({ ...passwordForm, newPassword: e.target.value })}
          />
          <Input
            type="password"
            placeholder={t("pages.settings.personal.password.confirmPassword")}
            value={passwordForm.confirmPassword}
            onChange={(e) => setPasswordForm({ ...passwordForm, confirmPassword: e.target.value })}
          />
        </div>
        <div className="mt-3 flex items-center justify-between gap-3">
          <p className="text-xs text-muted-warm">{t("pages.settings.personal.password.hint")}</p>
          <Button
            className="inline-flex items-center gap-2"
            onClick={() => changePasswordMutation.mutate()}
            disabled={!canSubmitPasswordChange || changePasswordMutation.isPending}
          >
            <KeyRound size={14} />
            {changePasswordMutation.isPending ? t("pages.settings.messages.saving") : t("pages.settings.personal.password.button")}
          </Button>
        </div>
        </Card>

        <Card>
          <h3 className="mb-3 text-base font-semibold">Saved Filters</h3>
        <div className="grid gap-2 md:grid-cols-[1fr_0.8fr_1.4fr_auto]">
          <Input placeholder="Filter name" value={filterName} onChange={(e) => setFilterName(e.target.value)} />
          <select className="field-warm h-11 rounded border px-3 text-sm outline-none focus:ring-2 focus:ring-[#bb9645]/25" value={filterScope} onChange={(e) => setFilterScope(e.target.value as SavedFilterScope)}>
            <option value="products">Products</option>
            <option value="inventory">Inventory</option>
            <option value="expiry">Expiry</option>
          </select>
          <Input placeholder="Query string, ex: search=fish&expiryStatus=WARNING_15" value={filterQuery} onChange={(e) => setFilterQuery(e.target.value)} />
          <Button onClick={() => createFilterMutation.mutate()} disabled={createFilterMutation.isPending || !filterName.trim()}>
            {createFilterMutation.isPending ? "Saving..." : "Save"}
          </Button>
        </div>

        <div className="mt-4 overflow-auto">
          <table className="table-warm w-full min-w-[940px] text-sm">
            <thead>
              <tr>
                <th className="px-3 py-2 text-left">Name</th>
                <th className="px-3 py-2 text-left">Scope</th>
                <th className="px-3 py-2 text-left">Query</th>
                <th className="px-3 py-2 text-right">Actions</th>
              </tr>
            </thead>
            <tbody>
              {savedFiltersQuery.isLoading ? (
                <tr><td colSpan={4} className="px-3 py-6 text-center text-muted-warm">Loading saved filters...</td></tr>
              ) : null}
              {!savedFiltersQuery.isLoading && !filterLinks.length ? (
                <tr><td colSpan={4} className="px-3 py-6 text-center text-muted-warm">No saved filters yet.</td></tr>
              ) : null}
              {filterLinks.map((f: any) => (
                <tr key={f.id} className="border-b">
                  <td className="px-3 py-2">{f.name}</td>
                  <td className="px-3 py-2 uppercase">{f.scope}</td>
                  <td className="px-3 py-2 text-xs text-[#6d5935]">
                    {Object.entries(f.query ?? {}).map(([k, v]) => `${k}=${v}`).join("&") || "-"}
                  </td>
                  <td className="px-3 py-2">
                    <div className="flex justify-end gap-2">
                      <Link to={f.href} className="btn-secondary-warm inline-flex h-9 items-center gap-1 rounded px-3 text-xs font-semibold">
                        <ExternalLink size={13} /> Open
                      </Link>
                      <button
                        className="btn-danger-warm inline-flex h-9 items-center gap-1 rounded px-3 text-xs font-semibold"
                        onClick={() => {
                          if (!window.confirm(`Delete saved filter "${f.name}"?`)) return;
                          deleteFilterMutation.mutate(f.id);
                        }}
                      >
                        <Trash2 size={13} /> Delete
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        </Card>

        {canEditSystem ? (
          <Card>
            <h3 className="mb-3 text-base font-semibold">Role Permission Matrix</h3>
            <div className="overflow-auto">
              <table className="table-warm w-full min-w-[760px] text-sm">
                <thead>
                  <tr>
                    <th className="px-3 py-2 text-left">Role</th>
                    <th className="px-3 py-2 text-left">Permissions</th>
                  </tr>
                </thead>
                <tbody>
                  {(permissionMatrixQuery.data?.data ?? []).map((row: any) => (
                    <tr key={row.role} className="border-b">
                      <td className="px-3 py-2 font-medium">{row.role}</td>
                      <td className="px-3 py-2 text-[#6d5935]">{(row.permissions ?? []).join(" | ")}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Card>
        ) : null}
      </section>
    </div>
  );
};


