import { randomUUID } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

export type SavedFilterScope = "products" | "inventory" | "expiry";

export interface SavedFilter {
  id: string;
  name: string;
  scope: SavedFilterScope;
  query: Record<string, string>;
  createdAt: string;
  updatedAt: string;
}

export interface SettingsPreferences {
  notifications: {
    approvalInApp: boolean;
    stockAlertEmail: boolean;
    expiryAlertEmail: boolean;
    dailySummaryEmail: boolean;
  };
  ui: {
    compactTables: boolean;
    defaultPageSize: number;
    currency: "USD";
    dateFormat: "MM/dd/yyyy";
  };
  roadmap: {
    aiPromoSuggestion: boolean;
    posScannerIntegration: boolean;
    advancedBiReports: boolean;
  };
}

export interface SystemSettings {
  profile: {
    storeName: string;
    branchName: string;
    address: string;
    contactPhone: string;
    contactEmail: string;
    taxCode: string;
  };
  operations: {
    lowStockThreshold: number;
    defaultReorderLevel: number;
    approvalBellRefreshSeconds: number;
    dashboardActivityRefreshSeconds: number;
    recentActivityLimit: number;
  };
  reports: {
    preparedBy: string;
    footerNote: string;
    includeContactInExport: boolean;
  };
}

export type SettingsPreferencesPatch = {
  notifications?: Partial<SettingsPreferences["notifications"]>;
  ui?: Partial<SettingsPreferences["ui"]>;
  roadmap?: Partial<SettingsPreferences["roadmap"]>;
};

export type SystemSettingsPatch = {
  profile?: Partial<SystemSettings["profile"]>;
  operations?: Partial<SystemSettings["operations"]>;
  reports?: Partial<SystemSettings["reports"]>;
};

interface UserSettingsRecord {
  preferences: SettingsPreferences;
  savedFilters: SavedFilter[];
  updatedAt: string;
}

interface SettingsStoreShape {
  users: Record<string, UserSettingsRecord>;
  system: SystemSettings;
}

const SETTINGS_FILE_PATH = fileURLToPath(new URL("../../../data/settings.json", import.meta.url));
let settingsStore: SettingsStoreShape | null = null;

const defaultPreferences = (): SettingsPreferences => ({
  notifications: {
    approvalInApp: true,
    stockAlertEmail: false,
    expiryAlertEmail: false,
    dailySummaryEmail: false,
  },
  ui: {
    compactTables: false,
    defaultPageSize: 20,
    currency: "USD",
    dateFormat: "MM/dd/yyyy",
  },
  roadmap: {
    aiPromoSuggestion: false,
    posScannerIntegration: false,
    advancedBiReports: false,
  },
});

const defaultRecord = (): UserSettingsRecord => ({
  preferences: defaultPreferences(),
  savedFilters: [],
  updatedAt: new Date().toISOString(),
});

const defaultSystemSettings = (): SystemSettings => ({
  profile: {
    storeName: "Smart Supermarket",
    branchName: "Main Branch",
    address: "",
    contactPhone: "",
    contactEmail: "",
    taxCode: "",
  },
  operations: {
    lowStockThreshold: 5,
    defaultReorderLevel: 5,
    approvalBellRefreshSeconds: 5,
    dashboardActivityRefreshSeconds: 4,
    recentActivityLimit: 5,
  },
  reports: {
    preparedBy: "Operations Manager",
    footerNote: "Generated by Smart Supermarket Product Management System.",
    includeContactInExport: true,
  },
});

const clampInt = (value: unknown, min: number, max: number, fallback: number) => {
  const num = Number(value);
  if (!Number.isFinite(num)) return fallback;
  return Math.min(max, Math.max(min, Math.round(num)));
};

const asString = (value: unknown, fallback = "") => (typeof value === "string" ? value : fallback);

const normalizeSystemSettings = (input?: Partial<SystemSettings>): SystemSettings => {
  const defaults = defaultSystemSettings();
  return {
    profile: {
      storeName: asString(input?.profile?.storeName, defaults.profile.storeName).trim() || defaults.profile.storeName,
      branchName: asString(input?.profile?.branchName, defaults.profile.branchName).trim() || defaults.profile.branchName,
      address: asString(input?.profile?.address, defaults.profile.address).trim(),
      contactPhone: asString(input?.profile?.contactPhone, defaults.profile.contactPhone).trim(),
      contactEmail: asString(input?.profile?.contactEmail, defaults.profile.contactEmail).trim(),
      taxCode: asString(input?.profile?.taxCode, defaults.profile.taxCode).trim(),
    },
    operations: {
      lowStockThreshold: clampInt(input?.operations?.lowStockThreshold, 0, 100000, defaults.operations.lowStockThreshold),
      defaultReorderLevel: clampInt(input?.operations?.defaultReorderLevel, 0, 100000, defaults.operations.defaultReorderLevel),
      approvalBellRefreshSeconds: clampInt(input?.operations?.approvalBellRefreshSeconds, 2, 120, defaults.operations.approvalBellRefreshSeconds),
      dashboardActivityRefreshSeconds: clampInt(input?.operations?.dashboardActivityRefreshSeconds, 2, 120, defaults.operations.dashboardActivityRefreshSeconds),
      recentActivityLimit: clampInt(input?.operations?.recentActivityLimit, 3, 30, defaults.operations.recentActivityLimit),
    },
    reports: {
      preparedBy: asString(input?.reports?.preparedBy, defaults.reports.preparedBy).trim() || defaults.reports.preparedBy,
      footerNote: asString(input?.reports?.footerNote, defaults.reports.footerNote).trim() || defaults.reports.footerNote,
      includeContactInExport: typeof input?.reports?.includeContactInExport === "boolean"
        ? input.reports.includeContactInExport
        : defaults.reports.includeContactInExport,
    },
  };
};

const ensureStoreLoaded = async () => {
  if (settingsStore) return settingsStore;

  await mkdir(path.dirname(SETTINGS_FILE_PATH), { recursive: true });
  try {
    const raw = await readFile(SETTINGS_FILE_PATH, "utf-8");
    const parsed = JSON.parse(raw) as Partial<SettingsStoreShape>;
    settingsStore = {
      users: parsed && typeof parsed.users === "object" && parsed.users ? parsed.users : {},
      system: normalizeSystemSettings(parsed?.system),
    };
  } catch {
    settingsStore = {
      users: {},
      system: defaultSystemSettings(),
    };
    await writeFile(SETTINGS_FILE_PATH, JSON.stringify(settingsStore, null, 2), "utf-8");
  }
  return settingsStore;
};

const persistStore = async () => {
  if (!settingsStore) return;
  await writeFile(SETTINGS_FILE_PATH, JSON.stringify(settingsStore, null, 2), "utf-8");
};

const ensureUserRecord = async (userId: string) => {
  const store = await ensureStoreLoaded();
  if (!store.users[userId]) {
    store.users[userId] = defaultRecord();
    await persistStore();
  }
  return store.users[userId];
};

export const getPreferences = async (userId: string) => {
  const record = await ensureUserRecord(userId);
  if (record.preferences.ui.currency !== "USD" || record.preferences.ui.dateFormat !== "MM/dd/yyyy") {
    record.preferences.ui.currency = "USD";
    record.preferences.ui.dateFormat = "MM/dd/yyyy";
    record.updatedAt = new Date().toISOString();
    await persistStore();
  }
  return record.preferences;
};

export const updatePreferences = async (userId: string, patch: SettingsPreferencesPatch) => {
  const record = await ensureUserRecord(userId);
  record.preferences = {
    notifications: {
      ...record.preferences.notifications,
      ...(patch.notifications ?? {}),
    },
    ui: {
      ...record.preferences.ui,
      ...(patch.ui ?? {}),
      currency: "USD",
      dateFormat: "MM/dd/yyyy",
    },
    roadmap: {
      ...record.preferences.roadmap,
      ...(patch.roadmap ?? {}),
    },
  };
  record.updatedAt = new Date().toISOString();
  await persistStore();
  return record.preferences;
};

export const getSystemSettings = async () => {
  const store = await ensureStoreLoaded();
  return store.system;
};

export const updateSystemSettings = async (patch: SystemSettingsPatch) => {
  const store = await ensureStoreLoaded();
  const merged = normalizeSystemSettings({
    profile: {
      ...store.system.profile,
      ...(patch.profile ?? {}),
    },
    operations: {
      ...store.system.operations,
      ...(patch.operations ?? {}),
    },
    reports: {
      ...store.system.reports,
      ...(patch.reports ?? {}),
    },
  });
  store.system = merged;
  await persistStore();
  return merged;
};

export const listSavedFilters = async (userId: string, scope?: SavedFilterScope) => {
  const record = await ensureUserRecord(userId);
  const list = [...record.savedFilters].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  return scope ? list.filter((f) => f.scope === scope) : list;
};

export const createSavedFilter = async (
  userId: string,
  input: { name: string; scope: SavedFilterScope; query: Record<string, string> },
) => {
  const record = await ensureUserRecord(userId);
  const now = new Date().toISOString();
  const saved: SavedFilter = {
    id: randomUUID(),
    name: input.name.trim(),
    scope: input.scope,
    query: input.query,
    createdAt: now,
    updatedAt: now,
  };
  record.savedFilters.unshift(saved);
  record.updatedAt = now;
  await persistStore();
  return saved;
};

export const deleteSavedFilter = async (userId: string, filterId: string) => {
  const record = await ensureUserRecord(userId);
  const before = record.savedFilters.length;
  record.savedFilters = record.savedFilters.filter((f) => f.id !== filterId);
  const removed = before !== record.savedFilters.length;
  if (removed) {
    record.updatedAt = new Date().toISOString();
    await persistStore();
  }
  return removed;
};
